### ISSUE TITLE
Checkbox animation

### ISSUE THREAD

**Issue by Watson-B** [ezl/todo#15]
@yassinya We talked about doing checkbox animations in Slack. Just posting it here for clarity's sake. What do you need from me to implement this? I did the following animations in After Effects, and can export as Json with Lottie but I'm happy to convert them to make it easy for you. Also, how long do you estimate it to take to implement checkbox animations?
![checkmarks](https://user-images.githubusercontent.com/65913664/155018318-8b258c38-b2c1-4996-87f6-6e0ba4bfb40f.gif)

**Comment by yassinya** [comment]
@Watson-B it would be great if you could export them and send me the Json files, I will be able to render them on the webpage using [lottie-web](https://github.com/airbnb/lottie-web). The strikethrough animation of the texts could be done with CSS

This wouldn’t take more than a day, but I’ll come back to this after I am done with the first 5 new issues because Eric told me to execute them in this order

**Comment by Watson-B** [comment]
[checkbox.zip](https://github.com/ezl/todo/files/8187737/checkbox.zip)
Also posted in slack, adding it here for records as well.
