### ISSUE TITLE
for web based one, put a fixed banner at bottom of screen every N loads that tells the user they should install the browser extension to get it in every tab

### ISSUE THREAD

**Issue by ezl** [ezl/todo#22]
https://www.figma.com/file/MHW4pKE13g4L46Tvq7i8TQ/Bad-To-Do?node-id=1075%3A2

**Comment by yassinya** [comment]
@ezl I just finished working on this, check it out and let me know your thoughts.

- I made it pick a random interval [10, 15, 20] to show the banner, instead of showing it at a fixed interval
- If the user clicks the link, they will be redirected to the corresponding store depending on the browser they are using
- It first checks if the user has the extension installed before prompting the user to install it

I also updated the extensions. I will email them to you as soon as possible!
