### ISSUE TITLE
fix bug: make it possible to see items without tags

### ISSUE THREAD

**Issue by ezl** [ezl/todo#95]
https://www.loom.com/share/e53b9edcdfe14cbda16db15384383851

**Comment by yassinya** [comment]
I see two behaviors:

1. Tasks without tags not showing up when one or more tags are selected.
Correct me if I am wrong @ezl , I believe that this is the expected behavior when filtering items by tags. They are not showing up because they don’t have one or all of the selected tags. 

1. Tasks not showing up if there are no tags selected (Not the expected behavior)
Unselecting all the tags (turning filtering off) should have displayed all the tasks regardless of whether they have a tag or not. This a bug

**Comment by yassinya** [comment]
@ezl I found what’s causing tasks that don’t have a tag to not appear (even when no visible tags are selected/active)

When you: 
- Select a tag and then remove its tasks WHILE that tag is selected
- Have “Hide tags without tasks” setting set to yes
- This will hide that tag while it is in SELECTED state, this means the filter is still considered active.

I’ll update it later today, it should not consider hidden tags when filtering
